apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: retailpulse-minio
spec:
  serviceName: retailpulse-minio
  replicas: 1
  selector:
    matchLabels:
      app: retailpulse-minio
  template:
    metadata:
      labels:
        app: retailpulse-minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2025-04-22T22-12-26Z
          args: ["server", "/data", "--console-address", ":9001"]
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: retailpulse-secrets
                  key: S3_ACCESS_KEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: retailpulse-secrets
                  key: S3_SECRET_KEY
          volumeMounts:
            - mountPath: /data
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: retailpulse-minio
spec:
  selector:
    app: retailpulse-minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
