import Link from 'next/link';import {ArrowRight,Mail,MapPin,MessageCircle} from 'lucide-react';
const copy:Record<string,[string,string,string[]]>={
about:['Our story','Clothing with a sense of place.',['Rangavali began with a simple belief: Indian craft deserves a modern, effortless expression. We work closely with makers and small ateliers to create pieces that feel deeply considered and easy to live in.','Our collections move at a human pace. From the first sketch to the final stitch, every detail is shaped by material, movement and the women who wear it.']],
contact:['We are here','How can we help?',['Our client care team is available Monday to Saturday, 10am–7pm IST. We would love to hear from you.']],
faq:['Client care','Frequently asked questions',['How long will my order take to arrive?','Can I return or exchange a style?','How do I find my Rangavali size?','Do you offer cash on delivery?']],
'shipping-policy':['Client care','Shipping policy',['Orders are typically dispatched within 1–2 business days. Complimentary standard shipping is available across India on orders above ₹1,999.','You will receive tracking details by email and SMS as soon as your order leaves our atelier.']],
'refund-policy':['Client care','Returns & refunds',['We accept eligible returns requested within seven days of delivery. Pieces must be unworn, unwashed, and returned with original tags.','Approved refunds are returned to the original payment method within 5–7 business days.']],
'privacy-policy':['Legal','Privacy policy',['We collect only the information necessary to provide and improve your shopping experience. Your personal data is handled with care and never sold.']],
terms:['Legal','Terms & conditions',['By accessing Rangavali, you agree to these terms. Product colours may vary slightly across displays, and availability is subject to change.']],
blog:['The journal','Notes on style and craft',['The art of dressing for yourself','Inside the atelier: the quiet work of detail','Five ways to rewear an occasion kurta']],
offers:['A little more to love','Private offers',['Welcome offer: enjoy 10% off your first order with code WELCOME10.','Festive Preview: early access for Rangavali members.']],
};
export function ContentPage({slug}:{slug:string}){const d=copy[slug]||['Rangavali','Designed around you.',['Explore a considered world of modern Indian clothing, thoughtful service and enduring craft.']];return <main><section className="bg-blush py-20 md:py-28"><div className="container"><p className="eyebrow">{d[0]}</p><h1 className="serif text-5xl md:text-7xl font-semibold max-w-3xl mt-4">{d[1]}</h1></div></section><section className="container py-16 md:py-24"><div className="max-w-3xl">{slug==='contact'&&<div className="grid md:grid-cols-3 gap-4 mb-12">{[[MessageCircle,'WhatsApp'],[Mail,'Email us'],[MapPin,'Store locator']].map(([I,t]:any)=><button key={t} className="rounded-2xl bg-blush p-6 text-left"><I className="text-wine"/><b className="block mt-4">{t}</b></button>)}</div>}{slug==='faq'?d[2].map(x=><details key={x} className="border-b py-6"><summary className="font-bold cursor-pointer flex justify-between">{x}<span>+</span></summary><p className="mt-4 text-black/55 leading-7">You can find all relevant details in your account, or contact our client care team for personal assistance.</p></details>):d[2].map((x,i)=><div key={i} className="mb-8"><h2 className={slug==='blog'?'serif text-3xl':''}>{x}</h2>{slug==='blog'&&<Link href="#" className="text-wine font-bold flex gap-2 mt-3">Read story <ArrowRight size={16}/></Link>}</div>)}</div></section></main>}
export function Account(){return <main className="min-h-[70vh] grid md:grid-cols-2"><div className="hidden md:block bg-cover bg-center" style={{backgroundImage:"url('/images/catalog/look-5.jpg')"}}/><div className="p-8 md:p-16 flex items-center"><form className="w-full max-w-md"><p className="eyebrow">Welcome to Rangavali</p><h1 className="title mt-3">Sign in</h1><p className="text-black/50 mt-3">View orders, save favourites, and checkout faster.</p><label className="block mt-7 text-xs font-bold">EMAIL OR MOBILE NUMBER</label><input className="w-full border rounded-xl p-3.5 mt-2 outline-wine" placeholder="you@example.com"/><button className="btn btn-dark w-full mt-4">Continue securely</button><div className="flex items-center gap-4 my-5 text-black/35"><hr className="flex-1"/>or<hr className="flex-1"/></div><button className="btn border w-full">Continue with Google</button><p className="text-center text-xs mt-6 text-black/45">New here? An account is created automatically.</p></form></div></main>}
